### PR TITLE
feat: configurable Coraza output

### PR DESCRIPTION
**Pull request by theseion**
A new `-log-file` flag enables configuration of the file where Coraza messages are written to.

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thanks @theseion and sorry for the late response. I wonder if something like https://coraza.io/docs/seclang/directives/#secdebuglog can be used?

**Comment by theseion** [comment]
Possibly. But I don't care about the debug messages, only about the rule output as we have it for httpd / nginx. From the Coraza docs it looks like it could work but I'm worried that there will be other messages in the log that could break the go-ftw parser.

**Comment by jcchavezs** [comment]
Are you looking for this kind of output? 

```
[logError][emergency] [client "127.0.0.1"] Coraza: Access denied (phase 1). Invalid id [file "default.conf"] [line "4"] [id "1"] [rev ""] [msg "Invalid id"] [data ""] [severity "emergency"] [ver ""] [maturity "0"] [accuracy "0"] [hostname ""] [uri "/hello?id=0"] [unique_id "rjNxXelDsGPhqHYcBWF"]
```
cc @m4tteoP

**Comment by theseion** [comment]
Yes, precisely.

**Comment by jcchavezs** [comment]
Ended up going with `-matched-rules-log` argument.

**Pull request merged**
