### PR TITLE
docs: improves readme for docker.

### PR DESCRIPTION
**Pull request by jcchavezs**

### CODE REVIEW

**Comment by RedXanadu** [comment]
Thank you @jcchavezs!

**Comment by jcchavezs** [comment]
Did it work?

**Comment by RedXanadu** [comment]
@jcchavezs

> Did it work?

I'm revisiting this again today, and unfortunately it doesn't seem to work :(

Maybe I'm missing something.

---

Testing the Go variant, I get:

```
$ go run github.com/jcchavezs/coraza-httpbin/cmd/coraza-httpbin@latest -directives ./directives.conf.example
2023/04/03 17:49:00 invalid WAF config from file: failed to parse string: failed to readfile: open path: invalid argument
exit status 1
```

That is with my directives set like so:

```
SecRuleEngine On
SecDebugLog /dev/stdout
SecDebugLogLevel 1
Include /home/xanadu/.git/coreruleset/crs-setup.conf.example
Include /home/xanadu/.git/coreruleset/rules/*.conf
```

---

Testing the Docker variant, I get:

```
$ sudo docker run ghcr.io/jcchavezs/coraza-httpbin:main
exec /usr/bin/coraza-httpbin: no such file or directory
```

**Comment by jcchavezs** [comment]
Looking into this.

**Comment by jcchavezs** [comment]
Hi @RedXanadu, thanks for the feedback and the error traces so I could reproduce the error. Unfortunately this is an issue with the file system as it does not like absolute paths. I tried different approaches and ended up creating [my own library](https://github.com/jcchavezs/mergefs) for merging filesystems because existing ones did have some opinions and did not implement all interfaces.

I will soon fix as soon as finish test the new merge library.

**Comment by jcchavezs** [comment]
@RedXanadu could you please try this branch https://github.com/jcchavezs/coraza-httpbin/pull/6?

**Comment by RedXanadu** [comment]
@jcchavezs No joy: I'm getting the same errors with that branch:

```
$ go run github.com/jcchavezs/coraza-httpbin/cmd/coraza-httpbin@latest -directives ./directives.conf.example
2023/04/13 17:12:45 invalid WAF config from file: failed to parse string: failed to readfile: open path: invalid argument
exit status 1
```

and

```
$ sudo docker run ghcr.io/jcchavezs/coraza-httpbin:main
exec /usr/bin/coraza-httpbin: no such file or directory
```

**Comment by jcchavezs** [comment]
Hi @RedXanadu I am sorry for not coming back earlier. I think the problem is that you are trying to run it from main (which did not include the changes in the PR). I merged the PR into `main` so you might want to try now. To make sure everything works as expected I added some tests in the PR (see https://github.com/jcchavezs/coraza-httpbin/blob/main/cmd/coraza-httpbin/main_test.go)

**Comment by RedXanadu** [comment]
Thanks @jcchavezs! Confirmed that this now works. This will make testing Coraza so much easier :grinning: 

One quick question: do I need to tweak httpbin to accept non-GET requests? POST requests aren't making it to CRS, it seems.

One of my usual CRS tests is
`curl localhost --data 'test=/bin/bash'`
but it isn't being detected: I'm just getting a 405 Method Not Allowed from somewhere (maybe httpbin?):

```
$ curl localhost:8080 -v -o/dev/null --data 'test=/bin/bash'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Length: 14
> Content-Type: application/x-www-form-urlencoded
> 
} [14 bytes data]
< HTTP/1.1 405 Method Not Allowed
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Mon, 17 Apr 2023 14:18:09 GMT
< Content-Length: 24
< 
{ [24 bytes data]
100    38  100    24  100    14   5083   2965 --:--:-- --:--:-- --:--:--  9500
* Connection #0 to host localhost left intact
```

**Comment by jcchavezs** [comment]
Interesting. Did you try with the default example config? Did you load the
coraza recommended conf? I wonder why get and post could get different
treatment.

**Comment by RedXanadu** [comment]
Yes, with the default directive file/config POST arguments are not causing CRS to flag.

What is the Coraza recommended conf? Is that an extra file that should be `Include`-d somewhere?

**Comment by jcchavezs** [comment]
Is secrequestbodyaccess enabled and or the content type correct?

**Comment by RedXanadu** [comment]
@jcchavezs Adding `SecRequestBodyAccess On` to `directives.conf.example` fixed it :smile: 

So, should this file be `Include`-d for `coraza-httpbin` to work correctly?
`https://github.com/corazawaf/coraza/blob/v3/dev/coraza.conf-recommended`

I would like to document how to use `coraza-httpbin` for testing Coraza, so if one of the steps must be
"Download and include the file `https://github.com/corazawaf/coraza/blob/v3/dev/coraza.conf-recommended`"
then I'll document it like that.

**Comment by jcchavezs** [comment]
Done https://github.com/jcchavezs/coraza-httpbin/pull/8

**Pull request merged**
